# CMAKE generated file: DO NOT EDIT!
# Generated by "MinGW Makefiles" Generator, CMake Version 4.3

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = "C:\Program Files\CMake\bin\cmake.exe"

# The command to remove a file.
RM = "C:\Program Files\CMake\bin\cmake.exe" -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = C:\Users\Samurai\Downloads\TesseractGameEngine-main

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = C:\Users\Samurai\Downloads\TesseractGameEngine-main

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	"C:\Program Files\CMake\bin\cmake-gui.exe" -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	"C:\Program Files\CMake\bin\cmake.exe" --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start C:\Users\Samurai\Downloads\TesseractGameEngine-main\CMakeFiles C:\Users\Samurai\Downloads\TesseractGameEngine-main\\CMakeFiles\progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start C:\Users\Samurai\Downloads\TesseractGameEngine-main\CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named teste

# Build rule for target.
teste: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 teste
.PHONY : teste

# fast build rule for target.
teste/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\teste.dir\build.make CMakeFiles/teste.dir/build
.PHONY : teste/fast

formas/cilindro/cilindro.obj: formas/cilindro/cilindro.cpp.obj
.PHONY : formas/cilindro/cilindro.obj

# target to build an object file
formas/cilindro/cilindro.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\teste.dir\build.make CMakeFiles/teste.dir/formas/cilindro/cilindro.cpp.obj
.PHONY : formas/cilindro/cilindro.cpp.obj

formas/cilindro/cilindro.i: formas/cilindro/cilindro.cpp.i
.PHONY : formas/cilindro/cilindro.i

# target to preprocess a source file
formas/cilindro/cilindro.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\teste.dir\build.make CMakeFiles/teste.dir/formas/cilindro/cilindro.cpp.i
.PHONY : formas/cilindro/cilindro.cpp.i

formas/cilindro/cilindro.s: formas/cilindro/cilindro.cpp.s
.PHONY : formas/cilindro/cilindro.s

# target to generate assembly for a file
formas/cilindro/cilindro.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\teste.dir\build.make CMakeFiles/teste.dir/formas/cilindro/cilindro.cpp.s
.PHONY : formas/cilindro/cilindro.cpp.s

formas/cone/cone.obj: formas/cone/cone.cpp.obj
.PHONY : formas/cone/cone.obj

# target to build an object file
formas/cone/cone.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\teste.dir\build.make CMakeFiles/teste.dir/formas/cone/cone.cpp.obj
.PHONY : formas/cone/cone.cpp.obj

formas/cone/cone.i: formas/cone/cone.cpp.i
.PHONY : formas/cone/cone.i

# target to preprocess a source file
formas/cone/cone.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\teste.dir\build.make CMakeFiles/teste.dir/formas/cone/cone.cpp.i
.PHONY : formas/cone/cone.cpp.i

formas/cone/cone.s: formas/cone/cone.cpp.s
.PHONY : formas/cone/cone.s

# target to generate assembly for a file
formas/cone/cone.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\teste.dir\build.make CMakeFiles/teste.dir/formas/cone/cone.cpp.s
.PHONY : formas/cone/cone.cpp.s

formas/cubo/cubo.obj: formas/cubo/cubo.cpp.obj
.PHONY : formas/cubo/cubo.obj

# target to build an object file
formas/cubo/cubo.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\teste.dir\build.make CMakeFiles/teste.dir/formas/cubo/cubo.cpp.obj
.PHONY : formas/cubo/cubo.cpp.obj

formas/cubo/cubo.i: formas/cubo/cubo.cpp.i
.PHONY : formas/cubo/cubo.i

# target to preprocess a source file
formas/cubo/cubo.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\teste.dir\build.make CMakeFiles/teste.dir/formas/cubo/cubo.cpp.i
.PHONY : formas/cubo/cubo.cpp.i

formas/cubo/cubo.s: formas/cubo/cubo.cpp.s
.PHONY : formas/cubo/cubo.s

# target to generate assembly for a file
formas/cubo/cubo.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\teste.dir\build.make CMakeFiles/teste.dir/formas/cubo/cubo.cpp.s
.PHONY : formas/cubo/cubo.cpp.s

formas/esfera/esfera.obj: formas/esfera/esfera.cpp.obj
.PHONY : formas/esfera/esfera.obj

# target to build an object file
formas/esfera/esfera.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\teste.dir\build.make CMakeFiles/teste.dir/formas/esfera/esfera.cpp.obj
.PHONY : formas/esfera/esfera.cpp.obj

formas/esfera/esfera.i: formas/esfera/esfera.cpp.i
.PHONY : formas/esfera/esfera.i

# target to preprocess a source file
formas/esfera/esfera.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\teste.dir\build.make CMakeFiles/teste.dir/formas/esfera/esfera.cpp.i
.PHONY : formas/esfera/esfera.cpp.i

formas/esfera/esfera.s: formas/esfera/esfera.cpp.s
.PHONY : formas/esfera/esfera.s

# target to generate assembly for a file
formas/esfera/esfera.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\teste.dir\build.make CMakeFiles/teste.dir/formas/esfera/esfera.cpp.s
.PHONY : formas/esfera/esfera.cpp.s

formas/forma.obj: formas/forma.cpp.obj
.PHONY : formas/forma.obj

# target to build an object file
formas/forma.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\teste.dir\build.make CMakeFiles/teste.dir/formas/forma.cpp.obj
.PHONY : formas/forma.cpp.obj

formas/forma.i: formas/forma.cpp.i
.PHONY : formas/forma.i

# target to preprocess a source file
formas/forma.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\teste.dir\build.make CMakeFiles/teste.dir/formas/forma.cpp.i
.PHONY : formas/forma.cpp.i

formas/forma.s: formas/forma.cpp.s
.PHONY : formas/forma.s

# target to generate assembly for a file
formas/forma.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\teste.dir\build.make CMakeFiles/teste.dir/formas/forma.cpp.s
.PHONY : formas/forma.cpp.s

pontos/ponto.obj: pontos/ponto.cpp.obj
.PHONY : pontos/ponto.obj

# target to build an object file
pontos/ponto.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\teste.dir\build.make CMakeFiles/teste.dir/pontos/ponto.cpp.obj
.PHONY : pontos/ponto.cpp.obj

pontos/ponto.i: pontos/ponto.cpp.i
.PHONY : pontos/ponto.i

# target to preprocess a source file
pontos/ponto.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\teste.dir\build.make CMakeFiles/teste.dir/pontos/ponto.cpp.i
.PHONY : pontos/ponto.cpp.i

pontos/ponto.s: pontos/ponto.cpp.s
.PHONY : pontos/ponto.s

# target to generate assembly for a file
pontos/ponto.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\teste.dir\build.make CMakeFiles/teste.dir/pontos/ponto.cpp.s
.PHONY : pontos/ponto.cpp.s

pontos/ponto3.obj: pontos/ponto3.cpp.obj
.PHONY : pontos/ponto3.obj

# target to build an object file
pontos/ponto3.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\teste.dir\build.make CMakeFiles/teste.dir/pontos/ponto3.cpp.obj
.PHONY : pontos/ponto3.cpp.obj

pontos/ponto3.i: pontos/ponto3.cpp.i
.PHONY : pontos/ponto3.i

# target to preprocess a source file
pontos/ponto3.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\teste.dir\build.make CMakeFiles/teste.dir/pontos/ponto3.cpp.i
.PHONY : pontos/ponto3.cpp.i

pontos/ponto3.s: pontos/ponto3.cpp.s
.PHONY : pontos/ponto3.s

# target to generate assembly for a file
pontos/ponto3.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\teste.dir\build.make CMakeFiles/teste.dir/pontos/ponto3.cpp.s
.PHONY : pontos/ponto3.cpp.s

teste.obj: teste.cpp.obj
.PHONY : teste.obj

# target to build an object file
teste.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\teste.dir\build.make CMakeFiles/teste.dir/teste.cpp.obj
.PHONY : teste.cpp.obj

teste.i: teste.cpp.i
.PHONY : teste.i

# target to preprocess a source file
teste.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\teste.dir\build.make CMakeFiles/teste.dir/teste.cpp.i
.PHONY : teste.cpp.i

teste.s: teste.cpp.s
.PHONY : teste.s

# target to generate assembly for a file
teste.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\teste.dir\build.make CMakeFiles/teste.dir/teste.cpp.s
.PHONY : teste.cpp.s

utils/Vec3.obj: utils/Vec3.cpp.obj
.PHONY : utils/Vec3.obj

# target to build an object file
utils/Vec3.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\teste.dir\build.make CMakeFiles/teste.dir/utils/Vec3.cpp.obj
.PHONY : utils/Vec3.cpp.obj

utils/Vec3.i: utils/Vec3.cpp.i
.PHONY : utils/Vec3.i

# target to preprocess a source file
utils/Vec3.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\teste.dir\build.make CMakeFiles/teste.dir/utils/Vec3.cpp.i
.PHONY : utils/Vec3.cpp.i

utils/Vec3.s: utils/Vec3.cpp.s
.PHONY : utils/Vec3.s

# target to generate assembly for a file
utils/Vec3.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\teste.dir\build.make CMakeFiles/teste.dir/utils/Vec3.cpp.s
.PHONY : utils/Vec3.cpp.s

utils/camera.obj: utils/camera.cpp.obj
.PHONY : utils/camera.obj

# target to build an object file
utils/camera.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\teste.dir\build.make CMakeFiles/teste.dir/utils/camera.cpp.obj
.PHONY : utils/camera.cpp.obj

utils/camera.i: utils/camera.cpp.i
.PHONY : utils/camera.i

# target to preprocess a source file
utils/camera.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\teste.dir\build.make CMakeFiles/teste.dir/utils/camera.cpp.i
.PHONY : utils/camera.cpp.i

utils/camera.s: utils/camera.cpp.s
.PHONY : utils/camera.s

# target to generate assembly for a file
utils/camera.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\teste.dir\build.make CMakeFiles/teste.dir/utils/camera.cpp.s
.PHONY : utils/camera.cpp.s

utils/janela.obj: utils/janela.cpp.obj
.PHONY : utils/janela.obj

# target to build an object file
utils/janela.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\teste.dir\build.make CMakeFiles/teste.dir/utils/janela.cpp.obj
.PHONY : utils/janela.cpp.obj

utils/janela.i: utils/janela.cpp.i
.PHONY : utils/janela.i

# target to preprocess a source file
utils/janela.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\teste.dir\build.make CMakeFiles/teste.dir/utils/janela.cpp.i
.PHONY : utils/janela.cpp.i

utils/janela.s: utils/janela.cpp.s
.PHONY : utils/janela.s

# target to generate assembly for a file
utils/janela.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\teste.dir\build.make CMakeFiles/teste.dir/utils/janela.cpp.s
.PHONY : utils/janela.cpp.s

# Help Target
help:
	@echo The following are some of the valid targets for this Makefile:
	@echo ... all (the default if no target is provided)
	@echo ... clean
	@echo ... depend
	@echo ... edit_cache
	@echo ... rebuild_cache
	@echo ... teste
	@echo ... formas/cilindro/cilindro.obj
	@echo ... formas/cilindro/cilindro.i
	@echo ... formas/cilindro/cilindro.s
	@echo ... formas/cone/cone.obj
	@echo ... formas/cone/cone.i
	@echo ... formas/cone/cone.s
	@echo ... formas/cubo/cubo.obj
	@echo ... formas/cubo/cubo.i
	@echo ... formas/cubo/cubo.s
	@echo ... formas/esfera/esfera.obj
	@echo ... formas/esfera/esfera.i
	@echo ... formas/esfera/esfera.s
	@echo ... formas/forma.obj
	@echo ... formas/forma.i
	@echo ... formas/forma.s
	@echo ... pontos/ponto.obj
	@echo ... pontos/ponto.i
	@echo ... pontos/ponto.s
	@echo ... pontos/ponto3.obj
	@echo ... pontos/ponto3.i
	@echo ... pontos/ponto3.s
	@echo ... teste.obj
	@echo ... teste.i
	@echo ... teste.s
	@echo ... utils/Vec3.obj
	@echo ... utils/Vec3.i
	@echo ... utils/Vec3.s
	@echo ... utils/camera.obj
	@echo ... utils/camera.i
	@echo ... utils/camera.s
	@echo ... utils/janela.obj
	@echo ... utils/janela.i
	@echo ... utils/janela.s
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 0
.PHONY : cmake_check_build_system

